# Generated by Django 5.2.17 on 2026-09-06 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.IntegerField()),
                ('event_type', models.CharField(choices=[('observation', 'Observation'), ('communication', 'Communication'), ('action', 'Action'), ('transaction', 'Transaction'), ('state_change', 'State Change'), ('system', 'System')], max_length=50)),
                ('action', models.CharField(blank=True, max_length=100)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='agents.agent')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='simulation.world')),
            ],
        ),
    ]
