# Generated by Django 5.2.17 on 2026-09-06 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('system_prompt', models.TextField()),
                ('goals', models.JSONField(default=list)),
                ('personality', models.JSONField(default=dict)),
                ('wallet', models.FloatField(default=100.0)),
                ('energy', models.FloatField(default=100.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='simulation.world')),
            ],
        ),
    ]
