# Generated by Django 5.2.17 on 2026-09-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='inventory',
            field=models.JSONField(default=dict),
        ),
    ]
