# Generated by Django 5.2.17 on 2026-09-06 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_type', models.CharField(default='observation', max_length=50)),
                ('content', models.JSONField(default=dict)),
                ('importance', models.IntegerField(default=1)),
                ('tick', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='agents.agent')),
            ],
            options={
                'ordering': ['-tick', '-created_at'],
            },
        ),
    ]
