# Generated by Django 5.2.17 on 2026-09-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agent_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='runtime',
            field=models.CharField(default='rule', max_length=50),
        ),
    ]
