# Generated by Django 5.2.17 on 2026-09-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agent_runtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='runtime',
        ),
        migrations.AddField(
            model_name='agent',
            name='runtime_type',
            field=models.CharField(default='rule', max_length=30),
        ),
    ]
