# Generated by Django 5.2.17 on 2026-09-06 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_agentmemory_experiment_agentmemory_related_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmemory',
            name='related_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_memories', to='agents.agent'),
        ),
    ]
