# Generated by Django 5.2.17 on 2026-09-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_alter_agentmemory_related_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='agent',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
