# Generated by Django 5.2.17 on 2026-09-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agent_role'),
        ('simulation', '0004_message_conversation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='intent',
            field=models.CharField(default='information', max_length=30),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='active', max_length=20)),
                ('topic', models.CharField(default='general', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(related_name='conversations', to='agents.agent')),
            ],
        ),
    ]
